### ISSUE TITLE
Do we have to link android if 0.60 and above?

### ISSUE THREAD

**Issue by Darren120** [gbumps/react-native-screenguard#35]
"React-native 0.60 and higher: just cd ios && pod install, no additional requirements."

Does this mean android doesn't need linking? Or do I still have to follow the manual steps for manual linking for android?

**Comment by gbumps** [comment]
On React Native 0.60 and above, FB introduced autolinking for Android. When you `npm install` or `yarn add` a React Native dependency, it will automatically linked all Android native code of that dependency (if existed) to your React Native project build target faster, instead of old React Native version 0.59 and below, you have to run `react-native link deps` several times after installation, which is time consuming.
