### ISSUE TITLE
Cannot prevent record on Modal ?

### ISSUE THREAD

**Issue by mthinh** [gbumps/react-native-screenguard#42]
# What ?
@gbumps 
- I tried to record and opened modal at the same time. Seem like we cannot prevent record the modal. Is there any workaround? My app mostly uses modal, and cannot be replaced with View . Thanks so much

**Comment by gbumps** [comment]
Please describe the version, and the Modal library you encountered the problem.

I'm running React native 0.71, iOS 17,  using `Modal` of React-native and `react-native-modal`, works normally.

**Comment by gbumps** [comment]
Please describe full detailed of react-native version, and the modal library in which you encountered the problem, what View or Component the Modal contains inside.

I've tested on both simulator and real device, with Modal turned on (from `react-native` and `react-native-modal`) screen recording and screen capturing cannot capture any content inside it.

**Comment by mthinh** [comment]
Sr @gbumps for lacking of info.
Its happening on Android. 
Im using react-native-modal

**Comment by gbumps** [comment]
Yep, probably encountered even though the FLAG_SECURE turned on. This has been reported [here](https://github.com/facebook/react-native/issues/38537) 

I might suggest for you a workaround for Android: Instead of using Modal, try to set the content inside a TouchableWithoutFeedback, set the style View overlay to absolute and position as you wish, and don't forget to set an animation for it when user tapped outside or pressing close.

**Comment by mthinh** [comment]
I faced this on iOS. The keyboard seems not be able to ve hidden
@gbumps
![image](https://github.com/gbumps/react-native-screenguard/assets/28992487/d479a8c4-7e8c-46e7-a719-8da5ac8aeea1)

**Comment by gbumps** [comment]
The keyboard or alerts which is part of the OS, covering these required deeper manipulation, harder techniques on the native side, which may result in rejection of your app. Beside, covering these doesn't mean anything at all.
