### ISSUE TITLE
Separate screen capture and screen recording

### ISSUE THREAD

**Issue by Simoon-F** [gbumps/react-native-screenguard#46]
hello, I found that after calling register, screen capture and screen recording are effective at the same time. I want to know how to separate them?

1. Allow screen capture, do not allow screen recording
2. Allow screen recording, do not allow screen capture

**Comment by Simoon-F** [comment]
@gbumps

**Comment by gbumps** [comment]
There's no way you can separate from them and this is not on roadmap due to:

1. Android callback on screen recording.
2. I think not necessary to do it as most usecases are tended to block full functionality instead of separate it.

For this case, you can register the protection filter with both callbacks,  and when screenshot or screen recording is triggered, you call `unregister`, and `register` with the other ones based on your need.

For example you want to block screenshot but screen recording is allowed, you `register` the filter with both screenshot and screenRecording callbacks, set a flag `isScreenFilterActived` to true. When screenshot is triggered, check the flag to reactivate the filter again, and `unregister` to deactivate the filter when screen recording is triggered.

**Comment by gbumps** [comment]
Hi @Simoon-F, after thinking about this for a while, I'll implement this on the next update. Refers to #120 for more info

**Comment by gbumps** [comment]
Released in `v2.0.0`
