### ISSUE TITLE
[Android] Crash with black screen

### ISSUE THREAD

**Issue by dziter** [gbumps/react-native-screenguard#78]
- Platform: Android
- React Native: 0.76

Output: Black screen then crash

**Comment by Inayat567** [comment]
Please provide snapshot of the code and error (if any)

**Comment by gbumps** [comment]
Hello @dziter, this error happened because you have not yet implemented code in `AndroidManifest.xml`

Reference [here](https://gbumps.github.io/react-native-screenguard/docs/getting-started/linking#post-installation-for-android) for more info.

Meanwhile, I'm finding another way to auto implement this code after installing the lib on the upcoming version. Will be fully described in doc.

Thanks and happy hacking!

**Comment by dziter** [comment]
Thanks for your reply @Inayat567 @gbumps 

You are right. I am surprised it works until now on Android without this step..
I also had to change register to registerWithoutEffect to be able to keep my TextInput working. Otherwise, the keyboard does not show as you explained it here: https://gbumps.github.io/react-native-screenguard/docs/limitation/

**Comment by gbumps** [comment]
hi @dziter, this issue has been completely resolved at `v1.0.9`. Now you only just install and run, no need to declare it anymore.

Thanks!
